markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: csy2994.github.com
title: csy's Blog
description: Android, Cocos2d, Java Web, Linux, reading...
author: 
email: csy2994@gmail.com
github: csy2994

config:
  js_dir:
  img_dir:
  css_dir:
